org: rayyungdev
app: aws-resume-alpha
service: aws-resume-alpha

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'
    - '!env/**'